### ISSUE TITLE
Error: Unable to initialize main class org.bukkit.craftbukkit.Main

### ISSUE THREAD

**Issue by Watghi** [PurpurMC/Tentacles#3]
I enter: git clone https://github.com/PurpurMC/Tentacles.git
Then: cd Tentacles/
./gradlew applypatches
./gradlew createReobfPaperclipJar
After that , it outputs these three errors to the terminal
![image](https://user-images.githubusercontent.com/95087767/160946774-5f1c0a4c-4088-491f-a3bb-2d1609d0ce04.png)
Also, when the kernel starts, the error
![image](https://user-images.githubusercontent.com/95087767/160946894-22db7cde-54d7-41c1-8db1-59414be41d23.png)

**Comment by encode42** [comment]
The "errors" in the first screenshot are just deprication warnings, nothing important.

I am unable to reproduce this issue, please provide more details. What jar are you running? Java version? The more info, the easier I'll be able to debug.

**Comment by Watghi** [comment]
OS ubuntu 20.04, java 17.0.2+8 jdk-headless, gradle 7.4

**Comment by Watghi** [comment]
And where to be .jar for the server after ./gradlew build ?

**Comment by encode42** [comment]
The `build` job does not yield a jarfile. Instead, two files will build into `build/libs/` when you run the `createReobfPaperclipJar` job. One is a `bundler` jar, the other is your `paperclip` jar. You'd want to run the `paperclip` jar.

Still unable to reproduce on EndeavourOS and Java Temurin-17.0.2+8.

**Comment by Watghi** [comment]
Okay, let's start from the beginning, because I think I made a mistake with the location of the jar file.
What should I do to get the server jar file?

**Comment by encode42** [comment]
The paperclip jar (`build/libs/purpur-paperclip-*.jar`) after running `./gradlew createReobfPaperclipJar`.

**Comment by Watghi** [comment]
And everything now has the right one .jar, for some reason it was not created earlier
